// Code generated by MockGen. DO NOT EDIT.
// Source: cache-storage.go
//
// Generated by this command:
//
//	mockgen -source=cache-storage.go -package=sdkversion -destination=cache-storage.mock.go
//

// Package sdkversion is a generated GoMock package.
package sdkversion

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheStorage is a mock of CacheStorage interface.
type MockCacheStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCacheStorageMockRecorder
}

// MockCacheStorageMockRecorder is the mock recorder for MockCacheStorage.
type MockCacheStorageMockRecorder struct {
	mock *MockCacheStorage
}

// NewMockCacheStorage creates a new mock instance.
func NewMockCacheStorage(ctrl *gomock.Controller) *MockCacheStorage {
	mock := &MockCacheStorage{ctrl: ctrl}
	mock.recorder = &MockCacheStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheStorage) EXPECT() *MockCacheStorageMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockCacheStorage) Load(ctx context.Context) map[VersionType][]SDKVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].(map[VersionType][]SDKVersion)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockCacheStorageMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCacheStorage)(nil).Load), ctx)
}

// Store mocks base method.
func (m *MockCacheStorage) Store(ctx context.Context, versions map[VersionType][]SDKVersion) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Store", ctx, versions)
}

// Store indicates an expected call of Store.
func (mr *MockCacheStorageMockRecorder) Store(ctx, versions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCacheStorage)(nil).Store), ctx, versions)
}

// String mocks base method.
func (m *MockCacheStorage) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockCacheStorageMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockCacheStorage)(nil).String))
}

// Valid mocks base method.
func (m *MockCacheStorage) Valid(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Valid", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Valid indicates an expected call of Valid.
func (mr *MockCacheStorageMockRecorder) Valid(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Valid", reflect.TypeOf((*MockCacheStorage)(nil).Valid), ctx)
}
