#file: noinspection SpellCheckingInspection
run:
  concurrency: 4

issues:
  exclude-dirs:
    - testdata

# https://golangci-lint.run/usage/configuration/#linters-configuration
linters-settings:
  gosec:
    exclude-generated: true
    severity: medium
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-names:
      - db
      - err
  ginkgolinter:
    force-expect-to: true
    validate-async-intervals: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  lll:
    line-length: 150

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gocritic
    - gocyclo
    - err113
    - goimports
    - mnd
    - lll
    - gomoddirectives
    - goprintffuncname
    #    - gochecknoinits
    - goconst
    - gosec
    - govet
    - grouper
    - misspell
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - wastedassign
    - tagliatelle
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - whitespace
    # TODO    - wrapcheck
    - wsl
    - ginkgolinter
    - interfacebloat
    - nonamedreturns
    - stylecheck
