// Code generated by MockGen. DO NOT EDIT.
// Source: plugin.go
//
// Generated by this command:
//
//	mockgen -source=plugin.go -package=plugin -destination=plugin.mock.go
//

// Package plugin is a generated GoMock package.
package plugin

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSDKMPlugin is a mock of SDKMPlugin interface.
type MockSDKMPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockSDKMPluginMockRecorder
}

// MockSDKMPluginMockRecorder is the mock recorder for MockSDKMPlugin.
type MockSDKMPluginMockRecorder struct {
	mock *MockSDKMPlugin
}

// NewMockSDKMPlugin creates a new mock instance.
func NewMockSDKMPlugin(ctrl *gomock.Controller) *MockSDKMPlugin {
	mock := &MockSDKMPlugin{ctrl: ctrl}
	mock.recorder = &MockSDKMPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSDKMPlugin) EXPECT() *MockSDKMPluginMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockSDKMPlugin) Current(ctx context.Context, baseDir string) (SDKVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx, baseDir)
	ret0, _ := ret[0].(SDKVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockSDKMPluginMockRecorder) Current(ctx, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockSDKMPlugin)(nil).Current), ctx, baseDir)
}

// Env mocks base method.
func (m *MockSDKMPlugin) Env(ctx context.Context, baseDir string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env", ctx, baseDir)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Env indicates an expected call of Env.
func (mr *MockSDKMPluginMockRecorder) Env(ctx, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockSDKMPlugin)(nil).Env), ctx, baseDir)
}

// EnvByVersion mocks base method.
func (m *MockSDKMPlugin) EnvByVersion(ctx context.Context, version string) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvByVersion", ctx, version)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// EnvByVersion indicates an expected call of EnvByVersion.
func (mr *MockSDKMPluginMockRecorder) EnvByVersion(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvByVersion", reflect.TypeOf((*MockSDKMPlugin)(nil).EnvByVersion), ctx, version)
}

// Exec mocks base method.
func (m *MockSDKMPlugin) Exec(ctx context.Context, baseDir string, stdIn io.Reader, stdOut, stdErr io.Writer, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, baseDir, stdIn, stdOut, stdErr, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockSDKMPluginMockRecorder) Exec(ctx, baseDir, stdIn, stdOut, stdErr, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSDKMPlugin)(nil).Exec), ctx, baseDir, stdIn, stdOut, stdErr, args)
}

// Install mocks base method.
func (m *MockSDKMPlugin) Install(ctx context.Context, baseDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, baseDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockSDKMPluginMockRecorder) Install(ctx, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockSDKMPlugin)(nil).Install), ctx, baseDir)
}

// InstallVersion mocks base method.
func (m *MockSDKMPlugin) InstallVersion(ctx context.Context, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallVersion", ctx, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallVersion indicates an expected call of InstallVersion.
func (mr *MockSDKMPluginMockRecorder) InstallVersion(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallVersion", reflect.TypeOf((*MockSDKMPlugin)(nil).InstallVersion), ctx, version)
}

// LatestVersion mocks base method.
func (m *MockSDKMPlugin) LatestVersion(ctx context.Context) SDKVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersion", ctx)
	ret0, _ := ret[0].(SDKVersion)
	return ret0
}

// LatestVersion indicates an expected call of LatestVersion.
func (mr *MockSDKMPluginMockRecorder) LatestVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersion", reflect.TypeOf((*MockSDKMPlugin)(nil).LatestVersion), ctx)
}

// LatestVersionByPrefix mocks base method.
func (m *MockSDKMPlugin) LatestVersionByPrefix(ctx context.Context, prefix string) (SDKVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersionByPrefix", ctx, prefix)
	ret0, _ := ret[0].(SDKVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestVersionByPrefix indicates an expected call of LatestVersionByPrefix.
func (mr *MockSDKMPluginMockRecorder) LatestVersionByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersionByPrefix", reflect.TypeOf((*MockSDKMPlugin)(nil).LatestVersionByPrefix), ctx, prefix)
}

// ListAllVersions mocks base method.
func (m *MockSDKMPlugin) ListAllVersions(ctx context.Context) []SDKVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllVersions", ctx)
	ret0, _ := ret[0].([]SDKVersion)
	return ret0
}

// ListAllVersions indicates an expected call of ListAllVersions.
func (mr *MockSDKMPluginMockRecorder) ListAllVersions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllVersions", reflect.TypeOf((*MockSDKMPlugin)(nil).ListAllVersions), ctx)
}

// ListAllVersionsByPrefix mocks base method.
func (m *MockSDKMPlugin) ListAllVersionsByPrefix(ctx context.Context, prefix string) []SDKVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllVersionsByPrefix", ctx, prefix)
	ret0, _ := ret[0].([]SDKVersion)
	return ret0
}

// ListAllVersionsByPrefix indicates an expected call of ListAllVersionsByPrefix.
func (mr *MockSDKMPluginMockRecorder) ListAllVersionsByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllVersionsByPrefix", reflect.TypeOf((*MockSDKMPlugin)(nil).ListAllVersionsByPrefix), ctx, prefix)
}

// WithBasePlugin mocks base method.
func (m *MockSDKMPlugin) WithBasePlugin(basePlugin BasePlugin) SDKMPlugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithBasePlugin", basePlugin)
	ret0, _ := ret[0].(SDKMPlugin)
	return ret0
}

// WithBasePlugin indicates an expected call of WithBasePlugin.
func (mr *MockSDKMPluginMockRecorder) WithBasePlugin(basePlugin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithBasePlugin", reflect.TypeOf((*MockSDKMPlugin)(nil).WithBasePlugin), basePlugin)
}

// WithVersions mocks base method.
func (m *MockSDKMPlugin) WithVersions(versions SDKVersions) SDKMPlugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithVersions", versions)
	ret0, _ := ret[0].(SDKMPlugin)
	return ret0
}

// WithVersions indicates an expected call of WithVersions.
func (mr *MockSDKMPluginMockRecorder) WithVersions(versions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithVersions", reflect.TypeOf((*MockSDKMPlugin)(nil).WithVersions), versions)
}
