name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - run: make go-multiple-os-distributions version="${{github.ref_name}}"

      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          allowUpdates: true
          removeArtifacts: true
          artifacts: "distributions/*.tar.gz"
