name: Tests

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test-gomod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go mod tidy && git diff --exit-code go.mod go.sum

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - run: make go-dependencies

      - run: make go-generate && git diff --exit-code

      - run: make go-all-tests

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/reports/junit-report.xml"
        if: always()

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/reports
          files: ./coverage-unit.out
          verbose: true
